// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: my_db.proto

#include "my_db.pb.h"
#include "my_db.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace mydb {

static const char* MyDB_method_names[] = {
  "/mydb.MyDB/Get",
  "/mydb.MyDB/Set",
};

std::unique_ptr< MyDB::Stub> MyDB::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MyDB::Stub> stub(new MyDB::Stub(channel, options));
  return stub;
}

MyDB::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Get_(MyDB_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Set_(MyDB_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MyDB::Stub::Get(::grpc::ClientContext* context, const ::mydb::EntryKey& request, ::mydb::Entry* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mydb::EntryKey, ::mydb::Entry, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void MyDB::Stub::async::Get(::grpc::ClientContext* context, const ::mydb::EntryKey* request, ::mydb::Entry* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mydb::EntryKey, ::mydb::Entry, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void MyDB::Stub::async::Get(::grpc::ClientContext* context, const ::mydb::EntryKey* request, ::mydb::Entry* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mydb::Entry>* MyDB::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::mydb::EntryKey& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mydb::Entry, ::mydb::EntryKey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mydb::Entry>* MyDB::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::mydb::EntryKey& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MyDB::Stub::Set(::grpc::ClientContext* context, const ::mydb::Entry& request, ::mydb::EntryKey* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mydb::Entry, ::mydb::EntryKey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Set_, context, request, response);
}

void MyDB::Stub::async::Set(::grpc::ClientContext* context, const ::mydb::Entry* request, ::mydb::EntryKey* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mydb::Entry, ::mydb::EntryKey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, std::move(f));
}

void MyDB::Stub::async::Set(::grpc::ClientContext* context, const ::mydb::Entry* request, ::mydb::EntryKey* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mydb::EntryKey>* MyDB::Stub::PrepareAsyncSetRaw(::grpc::ClientContext* context, const ::mydb::Entry& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mydb::EntryKey, ::mydb::Entry, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Set_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mydb::EntryKey>* MyDB::Stub::AsyncSetRaw(::grpc::ClientContext* context, const ::mydb::Entry& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

MyDB::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MyDB_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MyDB::Service, ::mydb::EntryKey, ::mydb::Entry, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MyDB::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mydb::EntryKey* req,
             ::mydb::Entry* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MyDB_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MyDB::Service, ::mydb::Entry, ::mydb::EntryKey, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MyDB::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mydb::Entry* req,
             ::mydb::EntryKey* resp) {
               return service->Set(ctx, req, resp);
             }, this)));
}

MyDB::Service::~Service() {
}

::grpc::Status MyDB::Service::Get(::grpc::ServerContext* context, const ::mydb::EntryKey* request, ::mydb::Entry* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MyDB::Service::Set(::grpc::ServerContext* context, const ::mydb::Entry* request, ::mydb::EntryKey* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mydb

